config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'welcome/index'

  get '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  get 'newsfeed', to: "colleges#newsfeed"
  get 'explore', to: "colleges#explore"

  resources :colleges do
    collection do
      get 'search/:school_name', to: "colleges#search"
      post 'select', :action => 'select_school', as: 'select'
    end
  end

  resources :users do
    resources :photos #undergrads will create and delete photos
    resources :bookmarks #students will bookmark and unbookmark colleges
  end

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :college
  belongs_to :student
end

app/models/college.rb
class College < ActiveRecord::Base
  include PgSearch

  has_many :bookmarks
  has_many :undergrads
  has_many :photos


  pg_search_scope :search_by_school_name,
  :against => [
    [:name, "A"],
    [:city, "B"]
    ],
    :using => {
      :tsearch => {:prefix => true},
    }


  end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :undergrad
  belongs_to :college
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

  belongs_to :follower, :class_name => "User"
  belongs_to :followed, :class_name => "User"

end

app/models/student.rb
class Student < User
  has_many :bookmarks
end

app/models/undergrad.rb
class Undergrad < User
  has_many :photos
  belongs_to :college

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password


# people the user has followed
  has_many :relationships, :class_name => "Relationship", :foreign_key => "follower_id"
  has_many :followeds, :through => :relationships

# people the user is following
  has_many :reverse_relationships, :class_name => "Relationship", :foreign_key => "followed_id"
  has_many :followers, :through => :reverse_relationships

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    @boookmarks = Bookmark.where(user_id: current_user.id)
  end

  def show
  end

  def new
    @bookmark = Bookmark.new(college_id: params[:id], user_id: current_user.id)
  end

  def create
    @bookmark = Bookmark.create(college_id: params[:id], user_id: current_user.id)
  end

  def edit
  end

  def update
  end

  def destroy
    @bookmark = Bookmark.where(college_id: params[:id], user_id: current_user.id)
    @bookmark.destroy
  end

end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController

  def index
  end

  def newsfeed
    @bookmarks = Bookmark.where(user_id: current_user.id)
    @selected_schools = []
    @bookmarks.each do |bookmark|
      @selected_schools << College.find(bookmark.college_id)
    end
    @selected_photos = []
    @selected_schools.each do |school|
      @selected_photos << Photo.where(college_id: school.id)
    end
  end

  def explore
    @selected_schools = []
    College.all.each do |college|
      if Bookmark.where(user_id: current_user.id, college_id: college.id) == nil
        @selected_schools << college
      end
    end
    @selected_photos = []
    @selected_schools.each do |school|
      @selected_photos << Photo.where(college_id: school.id)
    end
  end

  def show
    @college = College.find(params[:id])
    @photos = @college.photos
    # @people = Undergrad.where(college_id: @college.id)

    #include how many students have bookmarked it
    @num_bookmarks = Bookmark.where(college_id: @college.id).count
  end

  def search
    p params
    search_value = College.search_by_school_name(params[:school_name]).limit(10)
    render json: search_value
  end

  def select_school
    p "**************************"
    p params
    school = College.where(school_params)[0]
    p school
    if school
      redirect_to college_path(school)
    else
      flash[:errors] = "No results. Please try again."
      redirect_to root_url
    end
  end


  private
  def school_params
    params.require(:college).permit(:name)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Photo.all
    # @photos.sort! {|a, b| b.created_at <=> a.created_at}
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.create(url: params[:url], undergrad_id: params[:user_id])
    # college id and categories
    if @photo.save
      render json: @photo
    end
  end

  def destroy
    photo = Photo.find(params[:id])
    photo.destroy

    redirect_to :back
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to newsfeed_path

    else
      @error = {message: "Your username or password is invalid"}
      redirect_to :back
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_filter  :verify_authenticity_token

  def new
    @user = User.new
  end

  def create
    @user = User.new(type: params[:type], name: params[:name], email: params[:email], password: params[:password])
    if @user.save
      session[:user_id] = @user.id
      if @user.is_a? Undergrad
        redirect_to edit_user_path(@user)

      else @user.is_a? Student
        redirect_to newsfeed_path(@user)
      end

    else
      flash[:errors] = @user.errors.full_messages
      redirect_to :back
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(grade: params[:grade], activities: params[:activities], hometown: params[:hometown], major: params[:major], minor: params[:minor])
    redirect_to user_path(@user)
  end

  def destroy
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/index.html.erb
<h1>List of all of your bookmarks</h1>

app/views/colleges/_photo.js.erb
var photos = []

$(".upload-photo").on("click", function(){
  console.log("clicked");

  cloudinary.openUploadWidget({ cloud_name: 'keepyourfriendsclose', upload_preset: 'wqsntyaq', max_files: 1},

    function(error, result) {
      photos.push(result);

      var url = photos[(photos.length-1)][0].secure_url

      var user_id = $(".photo-stream").attr("data-user-id")
      $.ajax({
        url: "/users/"+user_id+"/photos",
        type: "post",
        dataType: "json",
        data: {url: url, user_id: user_id}
      }).done(function(response){
        console.log("success");
        console.log(response.url)
        $(".photo-stream").append("<div class='photo'>><img src="+response.url+"></div>")
      })
    });
})

app/views/colleges/explore.html.erb
<h1> Explore Colleges </h1>
<SPAN>that you arent following...</SPAN>

<div class="photo-stream", data-user-id="<%=current_user.id%>">
  <% @selected_photos.each do |photo|%>
    <div class="photo">
      <img src="<%= photo.url%>">

      <% if photo.undergrad_id == current_user.id %>
      <%= button_to "Delete", user_photo_path(current_user, photo), method: :delete %>
      <%end%>
    </div>

  <%end%>
</div>

app/views/colleges/newsfeed.html.erb
<h1> Your Colleges Newsfeed </h1>

<%if current_user.is_a? Undergrad%>
  <button><div class="upload-photo"> Upload a Photo </div></button>
<%end%>

<div class="photo-stream", data-user-id="<%=current_user.id%>">
  <% @selected_photos.each do |photo|%>
    <div class="photo">
      <img src="<%= photo.url%>">

      <% if photo.undergrad_id == current_user.id %>
      <%= button_to "Delete", user_photo_path(current_user, photo), method: :delete %>
      <%end%>
    </div>

  <%end%>
</div>


<script>
  <%= render "photo.js" %>
</script>

app/views/colleges/show.html.erb
<h1> College Show Page </h1>

<h1><%= @college.name%></h1>

<div class="photo-stream">
  <% @photos.each do |photo|%>
    <div class="photo">
      <img src="<%= photo.url%>">
    </div>
  <%end%>
</div>

<!-- include list of people who go to this school -->

app/views/photos/index.html.erb
<h1>photo index aka newsfeed</h1>

<%if current_user.is_a? Undergrad%>
  <div class="upload-photo"><button> Upload a Photo </button></div>
<%end%>

<div class="photo-stream", data-user-id="<%=current_user.id%>">
  <% @photos.each do |photo|%>
    <div class="photo">
      <img src="<%= photo.url%>">

      <% if photo.undergrad_id == current_user.id %>
      <%= button_to "Delete", user_photo_path(current_user, photo), method: :delete %>
      <%end%>
    </div>

  <%end%>
</div>

app/views/users/edit.html.erb
<h1>Profile Information</h1>

<%= form_for @user, url: user_path do |f| %>

  <%= f.label :college %>
  <%= f.text_field :college %><br>

  <%= f.label :grade %>
  <%= f.text_field :grade %><br>

  <%= f.label :hometown %>
  <%= f.text_field :hometown %><br>

  <%= f.label :activities %>
  <%= f.text_field :activities %><br>

  <%= f.label :major %>
  <%= f.text_field :major %><br>

  <%= f.label :minor %>
  <%= f.text_field :minor %><br>

<%= f.submit "Save Changes" %>
<% end %>

app/views/users/show.html.erb
<div class="profile-header">
  <%= current_user.name %> <br>
  <% if current_user.is_a? Undergrad%>
  <span> College Student</span>
  <!-- which school -->
  <%end%>
</div>


<!-- UNDERGRAD PROFILE  -->
<% if current_user.is_a? Undergrad%>

<div id="nav">
  <div class="btn-group btn-group-justified" role="group" aria-label="...">
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-default"> Photos</button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-default"> A Day in the Life</button>
    </div>
  </div>
</div>

<div class="photo-collection">
  <% @photos = Photo.where(undergrad_id: current_user.id) %>
  <% @photos.reverse.each do |photo|%>
  <div class="photo">
    <img src="<%= photo.url%>">
  </div>
  <%end%>
</div>
<%end%>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="container">
  <h1>Dabunk</h1>
  <p>The best way to discover the social scenes of colleges. <br> Log in or Register to browse schools and their students. </p>
  </div>

<div id="SessionForms">

  <div id="LoginForm">
  <form id="loginForm" action="/login">
    <input type="text" name="email" placeholder="Email"></input>
    <input type="password" name="password" placeholder="Password"></input>
    <button id="login">Login</button>
  </form>
  </div>

  <div id="RegisterForm">
  <span> Sign Up </span>
  <form id="registrationForm" action="/users" method="post">
    <input type="radio" name="type" value="student"> I'm in High School </input><br>

<input type="radio" name="type" value="undergrad"> I'm in College </input><br>


    <input type="text" name="type" placeholder="Student or Undergrad?"></input><br>
    <input type="text" name="name" placeholder="First and Last Name"></input><br>
    <input type="text" name="email" placeholder="Email"></input><br>
    <input type="password" name="password" placeholder="Password"></input><br><br>
    <button id="register">Sign Up </button><br>
  </form>
  </div>

</div>
</div>