config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'welcome/index'

  get '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  get 'newsfeed', to: "colleges#newsfeed"
  get 'explore', to: "colleges#explore"

  resources :colleges do
    collection do
      get 'search/:school_name', to: "colleges#search"
      post 'select', :action => 'select_school', as: 'select'
    end
  end

  resources :users do
    resources :photos #undergrads will create and delete photos
    resources :bookmarks #students will bookmark and unbookmark colleges
  end

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :college
  belongs_to :student
end

app/models/college.rb
class College < ActiveRecord::Base
  include PgSearch

  has_many :bookmarks
  has_many :undergrads
  has_many :photos


  pg_search_scope :search_by_school_name,
  :against => [
    [:name, "A"],
    [:city, "B"]
    ],
    :using => {
      :tsearch => {:prefix => true},
    }


  end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :undergrad
  belongs_to :college
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

  belongs_to :follower, :class_name => "User"
  belongs_to :followed, :class_name => "User"

end

app/models/student.rb
class Student < User
  has_many :bookmarks
end

app/models/undergrad.rb
class Undergrad < User
  has_many :photos
  belongs_to :college

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password


# people the user has followed
  has_many :relationships, :class_name => "Relationship", :foreign_key => "follower_id"
  has_many :followeds, :through => :relationships

# people the user is following
  has_many :reverse_relationships, :class_name => "Relationship", :foreign_key => "followed_id"
  has_many :followers, :through => :reverse_relationships

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    @boookmarks = Bookmark.where(user_id: current_user.id)
  end

  def show
  end

  def new
    @bookmark = Bookmark.new(college_id: params[:id], user_id: current_user.id)
  end

  def create
    @bookmark = Bookmark.create(college_id: params[:id], user_id: current_user.id)
  end

  def edit
  end

  def update
  end

  def destroy
    @bookmark = Bookmark.where(college_id: params[:id], user_id: current_user.id)
    @bookmark.destroy
  end

end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController

  def index
  end

  def newsfeed
    @bookmarks = Bookmark.where(user_id: current_user.id)
    @selected_schools = []
    @bookmarks.each do |bookmark|
      @selected_schools << College.find(bookmark.college_id)
    end
    @selected_photos = []
    @selected_schools.each do |school|
      @selected_photos << Photo.where(college_id: school.id)
    end
  end

  def explore
    @selected_schools = []
    College.all.each do |college|
      if Bookmark.where(user_id: current_user.id, college_id: college.id) == nil
        @selected_schools << college
      end
    end
    @selected_photos = []
    @selected_schools.each do |school|
      @selected_photos << Photo.where(college_id: school.id)
    end
  end

  def show
    @college = College.find(params[:id])
    @photos = @college.photos
    # @people = Undergrad.where(college_id: @college.id)

    #include how many students have bookmarked it
    @num_bookmarks = Bookmark.where(college_id: @college.id).count
  end

  def search
    p params
    search_value = College.search_by_school_name(params[:school_name]).limit(10)
    render json: search_value
  end

  def select_school
    p "**************************"
    p params
    school = College.where(school_params)[0]
    p school
    if school
      redirect_to college_path(school)
    else
      flash[:errors] = "No results. Please try again."
      redirect_to root_url
    end
  end


  private
  def school_params
    params.require(:college).permit(:name)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Photo.all
    # @photos.sort! {|a, b| b.created_at <=> a.created_at}
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.create(url: params[:url], undergrad_id: params[:user_id])
    # college id and categories
    if @photo.save
      render json: @photo
    end
  end

  def destroy
    photo = Photo.find(params[:id])
    photo.destroy

    redirect_to :back
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to newsfeed_path

    else
      @error = {message: "Your username or password is invalid"}
      redirect_to :back
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_filter  :verify_authenticity_token

  def new
    @user = User.new
  end

  def create
    @user = User.new(type: params[:type], name: params[:name], email: params[:email], password: params[:password])
    if @user.save
      session[:user_id] = @user.id
      if @user.is_a? Undergrad
        redirect_to edit_user_path(@user)

      else @user.is_a? Student
        redirect_to newsfeed_path(@user)
      end

    else
      flash[:errors] = @user.errors.full_messages
      redirect_to :back
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(grade: params[:grade], activities: params[:activities], hometown: params[:hometown], major: params[:major], minor: params[:minor])
    redirect_to user_path(@user)
  end

  def destroy
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dabunk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <script src="http://widget.cloudinary.com/global/all.js" type="text/javascript"></script>

  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>



</head>
<body>

  <% if current_user %>


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= newsfeed_path %>">Dabunk</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= explore_path %>"> Explore </a></li>
      </ul>


      <ul class="nav navbar-nav navbar-right">

      <ul class="nav navbar-nav">
        <li><a href="<%= newsfeed_path %>"> Home </a></li>
      </ul>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <%= current_user.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <%if current_user.is_a? Undergrad%>
            <li><a href="<%= user_path(current_user)%>">View Profile</a></li>
            <li><a href="<%= edit_user_path(current_user) %>">Edit Profile</a></li>
            <%end%>

            <%if current_user.is_a? Student%>
            <li><a href="<%= user_bookmarks_path(current_user)%>">View Bookmarks</a></li>
            <%end%>
            <li><a href="<%= logout_path %>">Logout</a></li>
          </ul>
        </li>
      </ul>

      <%= form_for "college", url: select_colleges_path,  :html => {class: "navbar-form navbar-right"}, action: "select_school" do |f| %>

        <div class="form-group">
          <%= f.text_field :name, placeholder: "Search for Colleges", class: "search-bar form-control" %>
        </div>

        <button type="submit" class="search-schools btn btn-default">Search</button>

      <%end%>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

  <%end%>
  <%= yield %>

</body>
</html>